"""
Summarizer Agent - Creates structured summaries of research findings
"""
import os
from typing import Dict

class SummarizerAgent:
    def __init__(self, model_name: str = "gpt-4"):
        """Initialize the Summarizer Agent"""
        self.openai_api_key = os.getenv("OPENAI_API_KEY")
        
        if not self.openai_api_key:
            raise ValueError("OPENAI_API_KEY not found in environment variables")
    
    def summarize_research(self, topic: str, research_data: Dict) -> Dict:
        """
        Create a structured summary of research findings
        
        Args:
            topic (str): The topic being researched
            research_data (Dict): Research results from the Research Agent
            
        Returns:
            Dict: Structured summary
        """
        try:
            # Extract research content
            research_content = research_data.get("research_results", "")
            
            # Create summary structure
            summary = {
                "topic": topic,
                "overview": "Summary overview will be generated by CrewAI",
                "key_concepts": "Key concepts will be extracted by CrewAI",
                "how_it_works": "Technical explanation will be provided by CrewAI",
                "applications": "Real-world applications will be listed by CrewAI",
                "related_topics": "Related concepts will be identified by CrewAI",
                "status": "success"
            }
            
            return summary
            
        except Exception as e:
            return {
                "topic": topic,
                "summary": f"Error during summarization: {str(e)}",
                "status": "error"
            } 